### PR TITLE
Multiple lab fixes

### PR DESCRIPTION
**Pull request by WigF1**
Multiple labs have been fixed to match current Entra and Intune UI.
Bitlocker lab now uses the correct settings catalog profile rather than relying on the 'old' templates-based page.
Autopilot lab uses SEA-WS3 as there is no point using Windows 10. Every delivery I do, I have students use a Win11 VM for the lab. 
Removed unnecessary indentations.

### CODE REVIEW

**Comment by WigF1** [comment]
@MSFT-rstearman - Any chance of getting this merged, please?

**Comment by MSFT-rstearman** [comment]
I am reviewing this and will apply the changes once I have finished the review.

**Comment by WigF1** [comment]
Thanks. 

Any rough ETA? It's been 4 weeks already.

**Comment by MSFT-rstearman** [comment]
Sorry for the delay. we are in the process of a full lab review and the existing pull request will affect the review and changes we are making to the labs. Once the review is completed, we will incorporate the suggested changes.

**Review by MSFT-rstearman — APPROVED** [review]
I have reviewed these changes and find no conflicts with our current changes to the labs.

**Pull request merged**
