### PR TITLE
Lab changes

### PR DESCRIPTION
**Pull request by WigF1**
Fixed invalid quotations and typos in Lab 0101
Changed various labs to reflect UI renaming in Entra admin center
Reordered Lab 0201 so the steps increase the chance of success and reducing SEA-CL2 restarts 
Removed the request to enable Azure AD Connect Cloud Sync for the SSPR lab

### CODE REVIEW

**Comment by WigF1** [comment]
@MSFT-rstearman @maquinl 

Please action when you can.

**Comment by WigF1** [comment]
@MSFT-rstearman @maquinl Any chance of getting this PR merged before third delivery tomorrow, please?

**Comment by craigbeeremct** [comment]
Bump. We are running this at least twice in the next three weeks, these edits need to be made.

**Comment by MSFT-rstearman** [comment]
Sorry for the delay. We are currently working on the rebranding for Entra. I will review this as soon as I can. Thank you for your patience.

**Comment by MSFT-rstearman** [comment]
upon reviewing the merge request we found that merging this request will conflict with the current rebranding changes. I have noted the changes in this pull request so that we can apply them to the changes we are currently working on.

**Comment by WigF1** [comment]
And how long are we looking at waiting for the rebranding? Most of the changes are affecting students *now*, the whole point of MCTs contributing is to ensure lab steps are up to date...

**Pull request closed without merging**
